export interface Player {
  name: string;
  username: string;
}

export const players: Player[] = [
  { name: "Kingsley", username: "Kontor001" },
  { name: "Hope", username: "Hoppei" },
  { name: "Oliver", username: "Emex1" },
  { name: "Victor", username: "Martin_the" },
  { name: "Anietie", username: "Jude_Ben" },
  { name: "Mavis", username: "Mavis1906" },
  { name: "Chidubem", username: "Barry26" },
  { name: "Favour", username: "iamfavour" },
  { name: "Godswill", username: "A_Godswill_E" },
  { name: "Daniel", username: "Dantheboyy1" },
  { name: "Favour", username: "donfavorr" },
  { name: "Borngreat", username: "Entropy65" },
  { name: "Timilehin", username: "Timii_lehin" },
  { name: "Kingsley", username: "Kdot44556" },
  { name: "Seunn", username: "seun_bade" },
  { name: "Favour", username: "Favourizo1" },
  { name: "Enoch", username: "21stPhenom" },
  { name: "Nkereuwem", username: "Fulgent47" },
  { name: "Chilaka", username: "chilax333" },
  { name: "Mover", username: "Xemover" },
];

export interface Round {
  round: number;
  date: string;
  games: [string, string][];
}

export const rounds: Round[] = [
  { round:1,  date:"Fri. 24th April",  games:[["Enoch (21stPhenom)","Hope (Hoppei)"],["Anietie (Jude_Ben)","Kingsley (Kdot44556)"],["Borngreat (Entropy65)","Chidubem (Barry26)"],["Favour (donfavorr)","Favour (iamfavour)"],["Mavis (Mavis1906)","Timilehin (Timii_lehin)"],["Nkereuwem (Fulgent47)","Kingsley (Kontor001)"],["Victor (Martin_the)","Seunn (seun_bade)"],["Mover (Xemover)","Chilaka (chilax333)"],["Daniel (Dantheboyy1)","Godswill (A_Godswill_E)"],["Favour (Favourizo1)","Oliver (Emex1)"]] },
  { round:2,  date:"Sun. 26th April",  games:[["Kingsley (Kdot44556)","Oliver (Emex1)"],["Godswill (A_Godswill_E)","Favour (iamfavour)"],["Chilaka (chilax333)","Enoch (21stPhenom)"],["Mavis (Mavis1906)","Favour (donfavorr)"],["Chidubem (Barry26)","Daniel (Dantheboyy1)"],["Anietie (Jude_Ben)","Borngreat (Entropy65)"],["Mover (Xemover)","Nkereuwem (Fulgent47)"],["Timilehin (Timii_lehin)","Victor (Martin_the)"],["Hope (Hoppei)","Seunn (seun_bade)"],["Kingsley (Kontor001)","Favour (Favourizo1)"]] },
  { round:3,  date:"Tue. 28th April",  games:[["Godswill (A_Godswill_E)","Mavis (Mavis1906)"],["Enoch (21stPhenom)","Mover (Xemover)"],["Kingsley (Kontor001)","Kingsley (Kdot44556)"],["Seunn (seun_bade)","Chilaka (chilax333)"],["Daniel (Dantheboyy1)","Anietie (Jude_Ben)"],["Oliver (Emex1)","Borngreat (Entropy65)"],["Favour (iamfavour)","Chidubem (Barry26)"],["Hope (Hoppei)","Timilehin (Timii_lehin)"],["Nkereuwem (Fulgent47)","Favour (Favourizo1)"],["Victor (Martin_the)","Favour (donfavorr)"]] },
  { round:4,  date:"Thu. 30th April",  games:[["Favour (iamfavour)","Anietie (Jude_Ben)"],["Kingsley (Kdot44556)","Nkereuwem (Fulgent47)"],["Favour (donfavorr)","Hope (Hoppei)"],["Chidubem (Barry26)","Mavis (Mavis1906)"],["Favour (Favourizo1)","Mover (Xemover)"],["Godswill (A_Godswill_E)","Victor (Martin_the)"],["Oliver (Emex1)","Daniel (Dantheboyy1)"],["Seunn (seun_bade)","Enoch (21stPhenom)"],["Borngreat (Entropy65)","Kingsley (Kontor001)"],["Chilaka (chilax333)","Timilehin (Timii_lehin)"]] },
  { round:5,  date:"Sat. 2nd May",  games:[["Hope (Hoppei)","Godswill (A_Godswill_E)"],["Mover (Xemover)","Seunn (seun_bade)"],["Favour (donfavorr)","Chilaka (chilax333)"],["Anietie (Jude_Ben)","Mavis (Mavis1906)"],["Daniel (Dantheboyy1)","Kingsley (Kontor001)"],["Oliver (Emex1)","Favour (iamfavour)"],["Kingsley (Kdot44556)","Favour (Favourizo1)"],["Borngreat (Entropy65)","Nkereuwem (Fulgent47)"],["Victor (Martin_the)","Chidubem (Barry26)"],["Timilehin (Timii_lehin)","Enoch (21stPhenom)"]] },
  { round:6,  date:"Mon. 4th May",  games:[["Enoch (21stPhenom)","Favour (donfavorr)"],["Nkereuwem (Fulgent47)","Daniel (Dantheboyy1)"],["Mavis (Mavis1906)","Oliver (Emex1)"],["Chidubem (Barry26)","Hope (Hoppei)"],["Seunn (seun_bade)","Timilehin (Timii_lehin)"],["Anietie (Jude_Ben)","Victor (Martin_the)"],["Favour (Favourizo1)","Borngreat (Entropy65)"],["Kingsley (Kontor001)","Favour (iamfavour)"],["Chilaka (chilax333)","Godswill (A_Godswill_E)"],["Mover (Xemover)","Kingsley (Kdot44556)"]] },
  { round:7,  date:"Wed. 6th May",  games:[["Godswill (A_Godswill_E)","Enoch (21stPhenom)"],["Kingsley (Kontor001)","Mavis (Mavis1906)"],["Timilehin (Timii_lehin)","Mover (Xemover)"],["Daniel (Dantheboyy1)","Favour (Favourizo1)"],["Favour (iamfavour)","Nkereuwem (Fulgent47)"],["Borngreat (Entropy65)","Kingsley (Kdot44556)"],["Seunn (seun_bade)","Favour (donfavorr)"],["Hope (Hoppei)","Anietie (Jude_Ben)"],["Chidubem (Barry26)","Chilaka (chilax333)"],["Victor (Martin_the)","Oliver (Emex1)"]] },
  { round:8,  date:"Fri. 8th May",  games:[["Nkereuwem (Fulgent47)","Mavis (Mavis1906)"],["Favour (donfavorr)","Timilehin (Timii_lehin)"],["Godswill (A_Godswill_E)","Seunn (seun_bade)"],["Kingsley (Kdot44556)","Daniel (Dantheboyy1)"],["Enoch (21stPhenom)","Chidubem (Barry26)"],["Mover (Xemover)","Borngreat (Entropy65)"],["Victor (Martin_the)","Kingsley (Kontor001)"],["Favour (Favourizo1)","Favour (iamfavour)"],["Chilaka (chilax333)","Anietie (Jude_Ben)"],["Oliver (Emex1)","Hope (Hoppei)"]] },
  { round:9,  date:"Sun. 10th May",  games:[["Anietie (Jude_Ben)","Enoch (21stPhenom)"],["Favour (iamfavour)","Kingsley (Kdot44556)"],["Mavis (Mavis1906)","Favour (Favourizo1)"],["Daniel (Dantheboyy1)","Borngreat (Entropy65)"],["Nkereuwem (Fulgent47)","Victor (Martin_the)"],["Favour (donfavorr)","Mover (Xemover)"],["Kingsley (Kontor001)","Hope (Hoppei)"],["Timilehin (Timii_lehin)","Godswill (A_Godswill_E)"],["Chilaka (chilax333)","Oliver (Emex1)"],["Chidubem (Barry26)","Seunn (seun_bade)"]] },
  { round:10, date:"Tue. 12th May",  games:[["Kingsley (Kdot44556)","Mavis (Mavis1906)"],["Oliver (Emex1)","Enoch (21stPhenom)"],["Timilehin (Timii_lehin)","Chidubem (Barry26)"],["Kingsley (Kontor001)","Chilaka (chilax333)"],["Hope (Hoppei)","Nkereuwem (Fulgent47)"],["Borngreat (Entropy65)","Favour (iamfavour)"],["Favour (Favourizo1)","Victor (Martin_the)"],["Seunn (seun_bade)","Anietie (Jude_Ben)"],["Favour (donfavorr)","Godswill (A_Godswill_E)"],["Mover (Xemover)","Daniel (Dantheboyy1)"]] },
  { round:11, date:"Thu. 14th May",  games:[["Favour (iamfavour)","Daniel (Dantheboyy1)"],["Oliver (Emex1)","Seunn (seun_bade)"],["Godswill (A_Godswill_E)","Mover (Xemover)"],["Mavis (Mavis1906)","Borngreat (Entropy65)"],["Victor (Martin_the)","Kingsley (Kdot44556)"],["Anietie (Jude_Ben)","Timilehin (Timii_lehin)"],["Enoch (21stPhenom)","Kingsley (Kontor001)"],["Nkereuwem (Fulgent47)","Chilaka (chilax333)"],["Favour (Favourizo1)","Hope (Hoppei)"],["Chidubem (Barry26)","Favour (donfavorr)"]] },
  { round:12, date:"Sat. 16th May",  games:[["Timilehin (Timii_lehin)","Oliver (Emex1)"],["Favour (donfavorr)","Anietie (Jude_Ben)"],["Borngreat (Entropy65)","Victor (Martin_the)"],["Mavis (Mavis1906)","Daniel (Dantheboyy1)"],["Favour (iamfavour)","Mover (Xemover)"],["Hope (Hoppei)","Kingsley (Kdot44556)"],["Enoch (21stPhenom)","Nkereuwem (Fulgent47)"],["Godswill (A_Godswill_E)","Chidubem (Barry26)"],["Seunn (seun_bade)","Kingsley (Kontor001)"],["Chilaka (chilax333)","Favour (Favourizo1)"]] },
  { round:13, date:"Mon. 18th May",  games:[["Oliver (Emex1)","Favour (donfavorr)"],["Mover (Xemover)","Chidubem (Barry26)"],["Kingsley (Kontor001)","Timilehin (Timii_lehin)"],["Nkereuwem (Fulgent47)","Seunn (seun_bade)"],["Kingsley (Kdot44556)","Chilaka (chilax333)"],["Enoch (21stPhenom)","Favour (Favourizo1)"],["Anietie (Jude_Ben)","Godswill (A_Godswill_E)"],["Daniel (Dantheboyy1)","Victor (Martin_the)"],["Mavis (Mavis1906)","Favour (iamfavour)"],["Borngreat (Entropy65)","Hope (Hoppei)"]] },
  { round:14, date:"Wed. 20th May",  games:[["Kingsley (Kdot44556)","Enoch (21stPhenom)"],["Mover (Xemover)","Mavis (Mavis1906)"],["Timilehin (Timii_lehin)","Nkereuwem (Fulgent47)"],["Hope (Hoppei)","Daniel (Dantheboyy1)"],["Kingsley (Kontor001)","Favour (donfavorr)"],["Godswill (A_Godswill_E)","Oliver (Emex1)"],["Favour (iamfavour)","Victor (Martin_the)"],["Chilaka (chilax333)","Borngreat (Entropy65)"],["Favour (Favourizo1)","Seunn (seun_bade)"],["Chidubem (Barry26)","Anietie (Jude_Ben)"]] },
  { round:15, date:"Fri. 22nd May",  games:[["Chidubem (Barry26)","Oliver (Emex1)"],["Nkereuwem (Fulgent47)","Favour (donfavorr)"],["Anietie (Jude_Ben)","Mover (Xemover)"],["Daniel (Dantheboyy1)","Chilaka (chilax333)"],["Victor (Martin_the)","Mavis (Mavis1906)"],["Enoch (21stPhenom)","Borngreat (Entropy65)"],["Kingsley (Kontor001)","Godswill (A_Godswill_E)"],["Timilehin (Timii_lehin)","Favour (Favourizo1)"],["Seunn (seun_bade)","Kingsley (Kdot44556)"],["Favour (iamfavour)","Hope (Hoppei)"]] },
  { round:16, date:"Sun. 24th May",  games:[["Kingsley (Kdot44556)","Timilehin (Timii_lehin)"],["Hope (Hoppei)","Mavis (Mavis1906)"],["Chidubem (Barry26)","Kingsley (Kontor001)"],["Daniel (Dantheboyy1)","Enoch (21stPhenom)"],["Favour (Favourizo1)","Favour (donfavorr)"],["Chilaka (chilax333)","Favour (iamfavour)"],["Godswill (A_Godswill_E)","Nkereuwem (Fulgent47)"],["Victor (Martin_the)","Mover (Xemover)"],["Oliver (Emex1)","Anietie (Jude_Ben)"],["Borngreat (Entropy65)","Seunn (seun_bade)"]] },
  { round:17, date:"Tue. 26th May",  games:[["Seunn (seun_bade)","Daniel (Dantheboyy1)"],["Nkereuwem (Fulgent47)","Chidubem (Barry26)"],["Hope (Hoppei)","Victor (Martin_the)"],["Favour (iamfavour)","Enoch (21stPhenom)"],["Favour (donfavorr)","Kingsley (Kdot44556)"],["Borngreat (Entropy65)","Timilehin (Timii_lehin)"],["Mavis (Mavis1906)","Chilaka (chilax333)"],["Oliver (Emex1)","Mover (Xemover)"],["Favour (Favourizo1)","Godswill (A_Godswill_E)"],["Anietie (Jude_Ben)","Kingsley (Kontor001)"]] },
  { round:18, date:"Thu. 28th May",  games:[["Chidubem (Barry26)","Favour (Favourizo1)"],["Anietie (Jude_Ben)","Nkereuwem (Fulgent47)"],["Chilaka (chilax333)","Victor (Martin_the)"],["Daniel (Dantheboyy1)","Timilehin (Timii_lehin)"],["Kingsley (Kontor001)","Oliver (Emex1)"],["Seunn (seun_bade)","Favour (iamfavour)"],["Mavis (Mavis1906)","Enoch (21stPhenom)"],["Kingsley (Kdot44556)","Godswill (A_Godswill_E)"],["Favour (donfavorr)","Borngreat (Entropy65)"],["Mover (Xemover)","Hope (Hoppei)"]] },
  { round:19, date:"Sat. 30th May",  games:[["Kingsley (Kdot44556)","Chidubem (Barry26)"],["Mavis (Mavis1906)","Seunn (seun_bade)"],["Hope (Hoppei)","Chilaka (chilax333)"],["Nkereuwem (Fulgent47)","Oliver (Emex1)"],["Borngreat (Entropy65)","Godswill (A_Godswill_E)"],["Timilehin (Timii_lehin)","Favour (iamfavour)"],["Favour (Favourizo1)","Anietie (Jude_Ben)"],["Mover (Xemover)","Kingsley (Kontor001)"],["Enoch (21stPhenom)","Victor (Martin_the)"],["Daniel (Dantheboyy1)","Favour (donfavorr)"]] },
  { round:20, date:"Mon. 1st June",  games:[["Chilaka (chilax333)","Mover (Xemover)"],["Hope (Hoppei)","Enoch (21stPhenom)"],["Oliver (Emex1)","Favour (Favourizo1)"],["Seunn (seun_bade)","Victor (Martin_the)"],["Chidubem (Barry26)","Borngreat (Entropy65)"],["Kingsley (Kdot44556)","Anietie (Jude_Ben)"],["Godswill (A_Godswill_E)","Daniel (Dantheboyy1)"],["Timilehin (Timii_lehin)","Mavis (Mavis1906)"],["Favour (iamfavour)","Favour (donfavorr)"],["Kingsley (Kontor001)","Nkereuwem (Fulgent47)"]] },
  { round:21, date:"Wed. 3rd June",  games:[["Favour (donfavorr)","Mavis (Mavis1906)"],["Borngreat (Entropy65)","Anietie (Jude_Ben)"],["Nkereuwem (Fulgent47)","Mover (Xemover)"],["Enoch (21stPhenom)","Chilaka (chilax333)"],["Seunn (seun_bade)","Hope (Hoppei)"],["Daniel (Dantheboyy1)","Chidubem (Barry26)"],["Favour (Favourizo1)","Kingsley (Kontor001)"],["Favour (iamfavour)","Godswill (A_Godswill_E)"],["Victor (Martin_the)","Timilehin (Timii_lehin)"],["Oliver (Emex1)","Kingsley (Kdot44556)"]] },
  { round:22, date:"Fri. 5th June",  games:[["Timilehin (Timii_lehin)","Hope (Hoppei)"],["Mavis (Mavis1906)","Godswill (A_Godswill_E)"],["Anietie (Jude_Ben)","Daniel (Dantheboyy1)"],["Chidubem (Barry26)","Favour (iamfavour)"],["Favour (Favourizo1)","Nkereuwem (Fulgent47)"],["Favour (donfavorr)","Victor (Martin_the)"],["Kingsley (Kdot44556)","Kingsley (Kontor001)"],["Borngreat (Entropy65)","Oliver (Emex1)"],["Chilaka (chilax333)","Seunn (seun_bade)"],["Mover (Xemover)","Enoch (21stPhenom)"]] },
  { round:23, date:"Sun. 7th June",  games:[["Daniel (Dantheboyy1)","Oliver (Emex1)"],["Mavis (Mavis1906)","Chidubem (Barry26)"],["Victor (Martin_the)","Godswill (A_Godswill_E)"],["Timilehin (Timii_lehin)","Chilaka (chilax333)"],["Anietie (Jude_Ben)","Favour (iamfavour)"],["Hope (Hoppei)","Favour (donfavorr)"],["Enoch (21stPhenom)","Seunn (seun_bade)"],["Nkereuwem (Fulgent47)","Kingsley (Kdot44556)"],["Mover (Xemover)","Favour (Favourizo1)"],["Kingsley (Kontor001)","Borngreat (Entropy65)"]] },
  { round:24, date:"Tue. 9th June",  games:[["Godswill (A_Godswill_E)","Hope (Hoppei)"],["Chidubem (Barry26)","Victor (Martin_the)"],["Nkereuwem (Fulgent47)","Borngreat (Entropy65)"],["Favour (Favourizo1)","Kingsley (Kdot44556)"],["Seunn (seun_bade)","Mover (Xemover)"],["Chilaka (chilax333)","Favour (donfavorr)"],["Favour (iamfavour)","Oliver (Emex1)"],["Mavis (Mavis1906)","Anietie (Jude_Ben)"],["Enoch (21stPhenom)","Timilehin (Timii_lehin)"],["Kingsley (Kontor001)","Daniel (Dantheboyy1)"]] },
  { round:25, date:"Thu. 11th June",  games:[["Kingsley (Kdot44556)","Mover (Xemover)"],["Favour (iamfavour)","Kingsley (Kontor001)"],["Borngreat (Entropy65)","Favour (Favourizo1)"],["Godswill (A_Godswill_E)","Chilaka (chilax333)"],["Oliver (Emex1)","Mavis (Mavis1906)"],["Hope (Hoppei)","Chidubem (Barry26)"],["Victor (Martin_the)","Anietie (Jude_Ben)"],["Daniel (Dantheboyy1)","Nkereuwem (Fulgent47)"],["Favour (donfavorr)","Enoch (21stPhenom)"],["Timilehin (Timii_lehin)","Seunn (seun_bade)"]] },
  { round:26, date:"Sat. 13th June",  games:[["Mavis (Mavis1906)","Kingsley (Kontor001)"],["Enoch (21stPhenom)","Godswill (A_Godswill_E)"],["Anietie (Jude_Ben)","Hope (Hoppei)"],["Favour (donfavorr)","Seunn (seun_bade)"],["Chilaka (chilax333)","Chidubem (Barry26)"],["Favour (Favourizo1)","Daniel (Dantheboyy1)"],["Kingsley (Kdot44556)","Borngreat (Entropy65)"],["Oliver (Emex1)","Victor (Martin_the)"],["Nkereuwem (Fulgent47)","Favour (iamfavour)"],["Mover (Xemover)","Timilehin (Timii_lehin)"]] },
  { round:27, date:"Mon. 15th June",  games:[["Kingsley (Kontor001)","Victor (Martin_the)"],["Borngreat (Entropy65)","Mover (Xemover)"],["Daniel (Dantheboyy1)","Kingsley (Kdot44556)"],["Anietie (Jude_Ben)","Chilaka (chilax333)"],["Favour (iamfavour)","Favour (Favourizo1)"],["Mavis (Mavis1906)","Nkereuwem (Fulgent47)"],["Chidubem (Barry26)","Enoch (21stPhenom)"],["Seunn (seun_bade)","Godswill (A_Godswill_E)"],["Hope (Hoppei)","Oliver (Emex1)"],["Timilehin (Timii_lehin)","Favour (donfavorr)"]] },
  { round:28, date:"Wed. 17th June",  games:[["Borngreat (Entropy65)","Daniel (Dantheboyy1)"],["Godswill (A_Godswill_E)","Timilehin (Timii_lehin)"],["Oliver (Emex1)","Chilaka (chilax333)"],["Kingsley (Kdot44556)","Favour (iamfavour)"],["Favour (Favourizo1)","Mavis (Mavis1906)"],["Seunn (seun_bade)","Chidubem (Barry26)"],["Hope (Hoppei)","Kingsley (Kontor001)"],["Mover (Xemover)","Favour (donfavorr)"],["Victor (Martin_the)","Nkereuwem (Fulgent47)"],["Enoch (21stPhenom)","Anietie (Jude_Ben)"]] },
  { round:29, date:"Fri. 19th June",  games:[["Chilaka (chilax333)","Kingsley (Kontor001)"],["Chidubem (Barry26)","Timilehin (Timii_lehin)"],["Mavis (Mavis1906)","Kingsley (Kdot44556)"],["Anietie (Jude_Ben)","Seunn (seun_bade)"],["Daniel (Dantheboyy1)","Mover (Xemover)"],["Godswill (A_Godswill_E)","Favour (donfavorr)"],["Nkereuwem (Fulgent47)","Hope (Hoppei)"],["Victor (Martin_the)","Favour (Favourizo1)"],["Favour (iamfavour)","Borngreat (Entropy65)"],["Enoch (21stPhenom)","Oliver (Emex1)"]] },
  { round:30, date:"Sun. 21st June",  games:[["Favour (donfavorr)","Chidubem (Barry26)"],["Hope (Hoppei)","Favour (Favourizo1)"],["Kingsley (Kdot44556)","Victor (Martin_the)"],["Seunn (seun_bade)","Oliver (Emex1)"],["Borngreat (Entropy65)","Mavis (Mavis1906)"],["Chilaka (chilax333)","Nkereuwem (Fulgent47)"],["Timilehin (Timii_lehin)","Anietie (Jude_Ben)"],["Mover (Xemover)","Godswill (A_Godswill_E)"],["Daniel (Dantheboyy1)","Favour (iamfavour)"],["Kingsley (Kontor001)","Enoch (21stPhenom)"]] },
  { round:31, date:"Tue. 23rd June",  games:[["Chidubem (Barry26)","Godswill (A_Godswill_E)"],["Victor (Martin_the)","Borngreat (Entropy65)"],["Kingsley (Kdot44556)","Hope (Hoppei)"],["Mover (Xemover)","Favour (iamfavour)"],["Favour (Favourizo1)","Chilaka (chilax333)"],["Daniel (Dantheboyy1)","Mavis (Mavis1906)"],["Kingsley (Kontor001)","Seunn (seun_bade)"],["Oliver (Emex1)","Timilehin (Timii_lehin)"],["Nkereuwem (Fulgent47)","Enoch (21stPhenom)"],["Anietie (Jude_Ben)","Favour (donfavorr)"]] },
  { round:32, date:"Thu. 25th June",  games:[["Godswill (A_Godswill_E)","Anietie (Jude_Ben)"],["Timilehin (Timii_lehin)","Kingsley (Kontor001)"],["Hope (Hoppei)","Borngreat (Entropy65)"],["Victor (Martin_the)","Daniel (Dantheboyy1)"],["Chidubem (Barry26)","Mover (Xemover)"],["Favour (Favourizo1)","Enoch (21stPhenom)"],["Favour (donfavorr)","Oliver (Emex1)"],["Favour (iamfavour)","Mavis (Mavis1906)"],["Seunn (seun_bade)","Nkereuwem (Fulgent47)"],["Chilaka (chilax333)","Kingsley (Kdot44556)"]] },
  { round:33, date:"Sat. 27th June",  games:[["Anietie (Jude_Ben)","Chidubem (Barry26)"],["Victor (Martin_the)","Favour (iamfavour)"],["Enoch (21stPhenom)","Kingsley (Kdot44556)"],["Nkereuwem (Fulgent47)","Timilehin (Timii_lehin)"],["Daniel (Dantheboyy1)","Hope (Hoppei)"],["Seunn (seun_bade)","Favour (Favourizo1)"],["Borngreat (Entropy65)","Chilaka (chilax333)"],["Oliver (Emex1)","Godswill (A_Godswill_E)"],["Favour (donfavorr)","Kingsley (Kontor001)"],["Mavis (Mavis1906)","Mover (Xemover)"]] },
  { round:34, date:"Mon. 29th June",  games:[["Borngreat (Entropy65)","Enoch (21stPhenom)"],["Kingsley (Kdot44556)","Seunn (seun_bade)"],["Favour (donfavorr)","Nkereuwem (Fulgent47)"],["Chilaka (chilax333)","Daniel (Dantheboyy1)"],["Favour (Favourizo1)","Timilehin (Timii_lehin)"],["Godswill (A_Godswill_E)","Kingsley (Kontor001)"],["Oliver (Emex1)","Chidubem (Barry26)"],["Hope (Hoppei)","Favour (iamfavour)"],["Mover (Xemover)","Anietie (Jude_Ben)"],["Mavis (Mavis1906)","Victor (Martin_the)"]] },
  { round:35, date:"Wed. 1st July",  games:[["Seunn (seun_bade)","Borngreat (Entropy65)"],["Favour (iamfavour)","Chilaka (chilax333)"],["Timilehin (Timii_lehin)","Kingsley (Kdot44556)"],["Kingsley (Kontor001)","Chidubem (Barry26)"],["Mover (Xemover)","Victor (Martin_the)"],["Favour (donfavorr)","Favour (Favourizo1)"],["Enoch (21stPhenom)","Daniel (Dantheboyy1)"],["Mavis (Mavis1906)","Hope (Hoppei)"],["Anietie (Jude_Ben)","Oliver (Emex1)"],["Nkereuwem (Fulgent47)","Godswill (A_Godswill_E)"]] },
  { round:36, date:"Fri. 3rd July",  games:[["Kingsley (Kdot44556)","Favour (donfavorr)"],["Chidubem (Barry26)","Nkereuwem (Fulgent47)"],["Timilehin (Timii_lehin)","Borngreat (Entropy65)"],["Chilaka (chilax333)","Mavis (Mavis1906)"],["Kingsley (Kontor001)","Anietie (Jude_Ben)"],["Mover (Xemover)","Oliver (Emex1)"],["Victor (Martin_the)","Hope (Hoppei)"],["Enoch (21stPhenom)","Favour (iamfavour)"],["Godswill (A_Godswill_E)","Favour (Favourizo1)"],["Daniel (Dantheboyy1)","Seunn (seun_bade)"]] },
  { round:37, date:"Sun. 5th July",  games:[["Favour (Favourizo1)","Chidubem (Barry26)"],["Hope (Hoppei)","Mover (Xemover)"],["Godswill (A_Godswill_E)","Kingsley (Kdot44556)"],["Enoch (21stPhenom)","Mavis (Mavis1906)"],["Victor (Martin_the)","Chilaka (chilax333)"],["Timilehin (Timii_lehin)","Daniel (Dantheboyy1)"],["Favour (iamfavour)","Seunn (seun_bade)"],["Borngreat (Entropy65)","Favour (donfavorr)"],["Oliver (Emex1)","Kingsley (Kontor001)"],["Nkereuwem (Fulgent47)","Anietie (Jude_Ben)"]] },
  { round:38, date:"Tue. 7th July",  games:[["Chidubem (Barry26)","Kingsley (Kdot44556)"],["Godswill (A_Godswill_E)","Borngreat (Entropy65)"],["Favour (donfavorr)","Daniel (Dantheboyy1)"],["Seunn (seun_bade)","Mavis (Mavis1906)"],["Anietie (Jude_Ben)","Favour (Favourizo1)"],["Favour (iamfavour)","Timilehin (Timii_lehin)"],["Kingsley (Kontor001)","Mover (Xemover)"],["Oliver (Emex1)","Nkereuwem (Fulgent47)"],["Chilaka (chilax333)","Hope (Hoppei)"],["Victor (Martin_the)","Enoch (21stPhenom)"]] },
];
